### ISSUE TITLE
Easy way make Distill fill JSON fields with rendered markup for AJAX responses

### ISSUE THREAD

**Issue by CopperBadger** [FursuiterNET/Fursuiter#12]
It's unavoidable that AJAX requests will need responses in JSON, which will frequently include rendered HTML. It doesn't look like there's an easy way to do this in Distill. Any tips?

**Comment by Dreae** [comment]
This can be done by accessing the Mako templating engine directly, something along the lines of:

```
from mako.template import Template

mytemplate = Template("hello, ${name}!")
print(mytemplate.render(name="jack"))
```

Or using files with:
```
mytemplate = Template(filename='/docs/mytmpl.txt')
print(mytemplate.render())
```

**Comment by CopperBadger** [comment]
Thanks! I'll try my hand at that next dev session

**Comment by CopperBadger** [comment]
Switched over to Angular so this isn't a problem anymore
